# Generated by Django 3.2.5 on 2021-07-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='practice_program_image')),
                ('program', models.TextField()),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('sel_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.subject')),
            ],
        ),
    ]
