# Generated by Django 3.2.5 on 2021-07-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='about_us_items_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('mobile1', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile3', models.CharField(blank=True, max_length=20, null=True)),
                ('website1', models.CharField(blank=True, max_length=100, null=True)),
                ('website2', models.CharField(blank=True, max_length=100, null=True)),
                ('website3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homepage_Discover_More_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='discover_more_images')),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_text', models.CharField(max_length=100)),
                ('heading_color', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('description_color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='homepage_slider_images')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
