# Generated by Django 3.2.5 on 2021-07-28 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operating_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumnail', models.ImageField(upload_to='project')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumnail', models.ImageField(blank=True, null=True, upload_to='Project_catagory_thumnail')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('enquiry', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sel_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
                ('sel_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='project_screenshot')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sel_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sel_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Operating_System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sel_operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.operating_system')),
                ('sel_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_module_image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sel_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('zip_file', models.FileField(upload_to='project_zip_files')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sel_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('offer_price', models.IntegerField()),
                ('helpline_number', models.IntegerField()),
                ('note', models.CharField(max_length=200)),
                ('synopsys', models.FileField(blank=True, null=True, upload_to='project_synopsys')),
                ('report', models.FileField(blank=True, null=True, upload_to='project_reports')),
                ('thesis', models.FileField(blank=True, null=True, upload_to='project_thesis')),
                ('presentation', models.FileField(blank=True, null=True, upload_to='project_presentation')),
                ('project_setup_video', models.FileField(blank=True, null=True, upload_to='project_setup_video')),
                ('project_overview_video', models.FileField(blank=True, null=True, upload_to='project_overview_video')),
                ('project_requirement_file', models.FileField(blank=True, null=True, upload_to='project_requirement_file')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sel_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='sel_project_catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.project_catagory'),
        ),
    ]
