# Generated by Django 3.2.5 on 2021-07-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('extra_description1', models.TextField(blank=True, null=True)),
                ('extra_description2', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('example_code', models.TextField(blank=True, null=True)),
                ('example_explained', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutorial_image')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('sel_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseapp.subject')),
                ('sel_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.topic')),
            ],
        ),
    ]
